// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8NxX5kPu5J058xzQHl-cGb3WkFMPD-HA',
    appId: '1:960566666260:web:98aaee2c9f092882b43301',
    messagingSenderId: '960566666260',
    projectId: 'chatapp-3fc03',
    authDomain: 'chatapp-3fc03.firebaseapp.com',
    storageBucket: 'chatapp-3fc03.firebasestorage.app',
    measurementId: 'G-SKCEESPZNT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDy50gH5Lntk3DlaQYk3L_sq4ITYtOVYY',
    appId: '1:960566666260:android:0b31ba0a44d4fc09b43301',
    messagingSenderId: '960566666260',
    projectId: 'chatapp-3fc03',
    storageBucket: 'chatapp-3fc03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoNIRX_3YJrY74pJECqIJGgXpMy2IcQgs',
    appId: '1:960566666260:ios:55ac60b55bc7bf77b43301',
    messagingSenderId: '960566666260',
    projectId: 'chatapp-3fc03',
    storageBucket: 'chatapp-3fc03.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoNIRX_3YJrY74pJECqIJGgXpMy2IcQgs',
    appId: '1:960566666260:ios:55ac60b55bc7bf77b43301',
    messagingSenderId: '960566666260',
    projectId: 'chatapp-3fc03',
    storageBucket: 'chatapp-3fc03.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8NxX5kPu5J058xzQHl-cGb3WkFMPD-HA',
    appId: '1:960566666260:web:79e90a28915c36f9b43301',
    messagingSenderId: '960566666260',
    projectId: 'chatapp-3fc03',
    authDomain: 'chatapp-3fc03.firebaseapp.com',
    storageBucket: 'chatapp-3fc03.firebasestorage.app',
    measurementId: 'G-R2WZK82LSX',
  );
}